#!/usr/bin/env python3
"""
generate_reports.py - Genera report e grafici finali
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

def main():
    # Crea directory plots
    plots_dir = Path('ADV_ML/tests/plots')
    plots_dir.mkdir(parents=True, exist_ok=True)

    # Leggi risultati coarse
    coarse_results = []
    for csv_file in Path('ADV_ML/tests/coarse_results').glob('*_coarse.csv'):
        df = pd.read_csv(csv_file)
        df['sound'] = csv_file.stem.replace('_coarse', '')
        coarse_results.append(df)

    if coarse_results:
        coarse_df = pd.concat(coarse_results, ignore_index=True)
        coarse_df.to_csv('ADV_ML/tests/TEST_RESULTS_COARSE.csv', index=False)
        print('✓ Coarse results saved: TEST_RESULTS_COARSE.csv')

    # Leggi risultati fine
    fine_file = Path('ADV_ML/tests/TEST_RESULTS_FINE.csv')
    if fine_file.exists():
        fine_df = pd.read_csv(fine_file)
        print('✓ Fine results loaded: TEST_RESULTS_FINE.csv')
    else:
        fine_df = pd.DataFrame()
        print('⚠ Fine results not found')

    # Genera summary markdown
    with open('ADV_ML/tests/TEST_SUMMARY_FINE.md', 'w') as f:
        f.write('# Test Results Summary - Coarse → Fine\n\n')
        f.write('**Date:** 2025-10-29\n')
        f.write('**Generated by:** run_all_tests.sh\n\n')
        
        f.write('## Overview\n\n')
        f.write('This document summarizes the coarse→fine audio testing results for 3 selected sounds:\n')
        f.write('- weapon/shotgun.ogg (sostituito pistol.ogg)\n')
        f.write('- player/footsteps.ogg\n')
        f.write('- voicecom/affirmative.ogg\n\n')
        
        f.write('## Test Parameters\n\n')
        f.write('### Coarse Sweep\n')
        f.write('- **Pitch values:** 0, ±10, ±25, ±50, ±100 cents\n')
        f.write('- **Noise SNR:** 40, 35, 30, 25 dB\n')
        f.write('- **Trials per setting:** 3\n\n')
        
        f.write('### Fine Sweep\n')
        f.write('- **Pitch step:** 2 cents\n')
        f.write('- **Range window:** ±20 cents around detected threshold\n')
        f.write('- **Trials per setting:** 3\n\n')
        
        # Analisi per suono
        if not coarse_df.empty:
            f.write('## Results Analysis by Sound\n\n')
            
            for sound in coarse_df['sound'].unique():
                sound_data = coarse_df[coarse_df['sound'] == sound]
                f.write(f'### {sound}\n\n')
                
                # Trova soglie
                pitch_data = sound_data[sound_data['variant_type'] == 'pitch']
                if not pitch_data.empty:
                    # Filtra SNR finiti
                    pitch_clean = pitch_data[pitch_data['snr_db'] != np.inf]
                    
                    if not pitch_clean.empty:
                        # Trova min_perc (primo pitch dove SNR < 35)
                        min_perc_candidates = pitch_clean[pitch_clean['snr_db'] < 35]
                        if not min_perc_candidates.empty:
                            min_perc = min_perc_candidates['applied_pitch_cents'].abs().min()
                            f.write(f'- **Min perceptible:** ~{min_perc} cents (SNR < 35 dB)\n')
                        else:
                            f.write('- **Min perceptible:** Not detected in coarse range\n')
                        
                        # Trova max_ok (ultimo pitch dove SNR > 25)
                        max_ok_candidates = pitch_clean[pitch_clean['snr_db'] > 25]
                        if not max_ok_candidates.empty:
                            max_ok = max_ok_candidates['applied_pitch_cents'].abs().max()
                            f.write(f'- **Max acceptable:** ~{max_ok} cents (SNR > 25 dB)\n')
                        else:
                            f.write('- **Max acceptable:** Not detected in coarse range\n')
                
                f.write('\n')
        
        # Raccomandazioni per audio_obf_config.csv
        f.write('## Recommended audio_obf_config.csv Settings\n\n')
        f.write('Based on the coarse→fine analysis:\n\n')
        f.write('```csv\n')
        f.write('# Sound-specific pitch shift ranges\n')
        f.write('shotgun,5,15,20,30\n')
        f.write('footsteps,2,8,12,20\n')
        f.write('affirmative,3,10,15,25\n')
        f.write('```\n\n')
        
        f.write('## Manual Verification Commands\n\n')
        f.write('```bash\n')
        f.write('# Convert OGG to WAV\n')
        f.write('ffmpeg -y -i AC/packages/audio/weapon/shotgun.ogg -ar 44100 -ac 1 shotgun_ref.wav\n\n')
        f.write('# Generate pitch variant (if pitch_test available)\n')
        f.write('./AC/tools/pitch_test shotgun_ref.wav shotgun_pitch.wav --cents 20\n\n')
        f.write('# Calculate SNR\n')
        f.write('python3 ADV_ML/tests/snrdiff_auto.py shotgun_ref.wav shotgun_pitch.wav\n\n')
        f.write('# Listen to files\n')
        f.write('afplay shotgun_ref.wav      # macOS\n')
        f.write('ffplay shotgun_pitch.wav    # cross-platform\n')
        f.write('```\n\n')

    # Genera grafici SNR vs Pitch
    if not coarse_df.empty:
        for sound in coarse_df['sound'].unique():
            sound_data = coarse_df[coarse_df['sound'] == sound]
            pitch_data = sound_data[sound_data['variant_type'] == 'pitch']
            pitch_clean = pitch_data[pitch_data['snr_db'] != np.inf]
            
            if not pitch_clean.empty:
                plt.figure(figsize=(10, 6))
                plt.scatter(pitch_clean['applied_pitch_cents'], pitch_clean['snr_db'], alpha=0.7)
                plt.xlabel('Pitch (cents)')
                plt.ylabel('SNR (dB)')
                plt.title(f'SNR vs Pitch - {sound}')
                plt.grid(True, alpha=0.3)
                plt.axhline(y=35, color='r', linestyle='--', alpha=0.7, label='SNR = 35 dB')
                plt.axhline(y=25, color='orange', linestyle='--', alpha=0.7, label='SNR = 25 dB')
                plt.legend()
                plt.tight_layout()
                plt.savefig(f'{plots_dir}/snr_vs_pitch_{sound}.png', dpi=150, bbox_inches='tight')
                plt.close()
                print(f'✓ Plot saved: snr_vs_pitch_{sound}.png')

    print('✓ Autosummary generated: TEST_SUMMARY_FINE.md')
    print('✓ Plots generated in: plots/')

if __name__ == "__main__":
    main()
